- Housing
- Economic Justice
- Education
- Health
- Immigration
- Criminal Justice
- Environment & Climate
- Civil Rights
- Workforce Development
- Food Security
- Gender-Based Violence
- Reproductive Rights
- LGBTQ+ Rights
- Other
